### PR TITLE
added cfaV1Forwarder address to networks

### PR DESCRIPTION
**Pull request by surewht**

### CODE REVIEW

**Review by d10r — CHANGES_REQUESTED** [review]
please add to all networks.
Also, after editing this file you need to locally run ./build.sh and commit all changes.

**Comment by hellwolf** [comment]
@tokdaniel side note, do you have some idea how to remove the need of the build.sh?

**Comment by surewht** [comment]
> @tokdaniel side note, do you have some idea how to remove the need of the build.sh?

we could add a bundler for npm packages e.g tsup worked for me always, also you can run it in CI/CD (on push) so you don't have to do it manually, but you could do the same with the build.sh as well

https://github.com/egoist/tsup

**Comment by hellwolf** [comment]
> > @tokdaniel side note, do you have some idea how to remove the need of the build.sh?
> 
> we could add a bundler for npm packages e.g tsup worked for me always, also you can run it in CI/CD (on push) so you don't have to do it manually, but you could do the same with the build.sh as well
> 
> https://github.com/egoist/tsup

At the moment, we don't release npm package for this package for simplicity. So everything is exposed as a git repo to package manager isntead.

**Comment by surewht** [comment]
> > > @tokdaniel side note, do you have some idea how to remove the need of the build.sh?
> > 
> > 
> > we could add a bundler for npm packages e.g tsup worked for me always, also you can run it in CI/CD (on push) so you don't have to do it manually, but you could do the same with the build.sh as well
> > https://github.com/egoist/tsup
> 
> At the moment, we don't release npm package for this package for simplicity. So everything is exposed as a git repo to package manager isntead.

that's not a problem, it's just a bundling tool, the repo could be used as before (at least I think?).

**Review by d10r — APPROVED** [review]

**Pull request merged**
